print("=== The Ultimate Wacky Recipe Maker ===")
print()
food = input("Please name some food: ")
plant = input("Can you please name a plant: ")
cooking = input("Name a method of cooking: ")
burned = input("How would you describe burnt food: ")
item = input("Can you please name a household item: ")
print()
print(f'How about {cooking} {food} with {burned} {plant} on a bed of {item}')